### ISSUE TITLE
Default module configuration missing status codes

### ISSUE THREAD

**Issue by brokoli18** [cloudalchemy/ansible-blackbox-exporter#32]
When deploying the exporter by default the module configuration looks like below:
```
modules:
  http_2xx:
    http: null
    prober: http
    timeout: 5s
```
When it is like this all Prometheus queries from the exporter return 0, whether or not they are reachable. This happens because most of the config for the variable `blackbox_exporter_configuration_modules` in the defaults file is commented out, and the README doesn't specify that variable as something that must be defined. There should be some sane values in the defaults file, eg:
```
blackbox_exporter_configuration_modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:      
      valid_status_codes: []
      method: GET
```
